# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6eef736834c0ab987a7dff6b1eea26eb93ae2578c500141ec1fb9dcab8aac28a120d617b8cce8b62bdb24f6f2709841057d153a5e25cd1563135eb4a4c1680b

test:
  secret_key_base: df64ca622b2352cf051d3ce8510c67fc2005edc7d3ecaab1761cc28e2175b6d2ecc9d1ded34c7618e2367d953efd6a956b3ad6d9c46d1bb7b62a6a52e3e47370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
